### ISSUE TITLE
Document custom resource templates

### ISSUE THREAD

**Issue by ismasan** [bootic/Bootic-Wiki#5]
## What

Document "secret" feature where custom HTML templates can be created for specific resources.

Example:
- collection with slug "my-collection" -> `collection-my-collection.html`
- product type with slug "laptops" -> `type-laptops.html`
- form with slug "contact" -> `form-contact.html`

Etc.
## Why

This is a powerful featured that has existed for a while, but is now stable and well tested in new Storefronts app.
## How

Almost all URLs that handle a single resource (product, collection, type, form, post, etc) support this.

In bootic/bootic_storefronts this can be seen in the code, in _renderer_ classes in `lib/renderers`. Example: https://github.com/bootic/bootic_storefronts/blob/master/lib/renderers/product_type_renderer.rb#L5

**Comment by tomas** [comment]
:+1:
